-- holyduck_mariadb_tables.sql
--
-- MariaDB table stubs for DuckDB-native views defined in holyduck_duckdb_extensions.sql.
--
-- When you create a view inside DuckDB (in holyduck_duckdb_extensions.sql), MariaDB has
-- no knowledge of it. To make it queryable through MariaDB, register a matching table
-- stub here with ENGINE=DUCKDB. MariaDB will treat it as a table; DuckDB will resolve
-- it against the view definition.
--
-- Install once per database:
--   mariadb -uroot -p mydb < holyduck_mariadb_tables.sql
--
-- Naming convention: prefix view stubs with "v_". HolyDuck skips DuckDB
-- table creation for any table named v_*, leaving the DuckDB view intact.
-- Column definitions must match the view's output columns and types.
--

-- ---------------------------------------------------------------------------
-- Example: a DuckDB view registered as a MariaDB table stub
--
-- Corresponding view in holyduck_duckdb_extensions.sql:
--   CREATE OR REPLACE VIEW mydb.v_my_view AS
--       SELECT id, val * 2 AS double_val FROM mydb.my_table;
--
-- CREATE TABLE IF NOT EXISTS v_my_view (
--     id         INT,
--     double_val DOUBLE
-- ) ENGINE=DUCKDB;
-- ---------------------------------------------------------------------------
